version: 0.0
os: linux
files:
  # 인스턴스에 복사 할 파일 or 디렉터리
  - source: /
  # 리눅스 최상위 dir -> root -> application
    destination: /root/application
    overwrite: yes

permissions:
  - object: /root/application
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
  - location: deploy.sh
    timeout: 180
    runas: root