version: 0.0
os: linux
files:
  # 인스턴스에 복사 할 파일 or 디렉터리
  - source: /
  # /home/root 우분투 home 디렉터리 /home/유저명
    destination: /home/root/application
    overwrite: yes

permissions:
  - object: /home/root/application
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
  - location: deploy.sh
    timeout: 180
    runas: root