version: 0.0
os: linux
files:
  - source: /
    destination: /S3_BUILD
    overwrite: yes

permissions:
  - object: /S3_BUILD
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
  - location: deploy.sh
    timeout: 180
    runas: root