server:
  port: 6550

spring:
  # db connection : MySql
  datasource:
    url: jdbc:mysql://localhost:5281/localdbA?serverTimezone=Asia/Seoul
    username: userlia
    password: mysqlpw293.
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true