name: CI/CD

# 지정한 branch ([main])에서 command(pull)가 수행되면 이 workflow가 동작
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # trigger 없어도 수동으로 동작
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout release
      uses: actions/checkout@v3

    - name: Set up Jdk 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: "adopt"

    - name: application yml
      run: touch ./src/main/resources/application.yml
    - run: echo "${{secrets.APPLICATION}}" > ./src/main/resources/application.yml
    - run: touch ./src/main/resources/application-server.yml
    - run: echo "${{secrets.APPLICATION_SERVER}}" > ./src/main/resources/application-server.yml
    - uses: actions/upload-artifact@v3
      with:
        name: application.yml
        path: ./src/main/resources/application.yml
    - uses: actions/upload-artifact@v3
      with:
        name: application-server.yml
        path: ./src/main/resources/application-server.yml

    - name: Grant excute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash

    - name: Build Gradle
      run: ./gradlew build -Dspring.profiles.include=server
      shell: bash

    # qq == 출력 x , r == 하위 폴더 같이 압축
    - name: Make zip file
      run: zip -qq -r ./${{ secrets.ZIP_NAME }}.zip .
      shell: bash

    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-key-id: ${{ secrets.SECRET_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Upload to S3
      run: aws s3 --region ap-northeast-2 ./${{ secrets.ZIP_NAME }}.zip s3://${{ secrets.S3_BUCKET }}/${{ secrets.PROJECT_NAME }}/${{ secrets.ZIP_NAME }}.zip

    - name: Code Deploy
      run: aws deploy create-deployment --application-name code_deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name github_active_group --s3-location bucket=code_deploy,bundleType=zip,key=${{ secrets.PROJECT_NAME }}/${{ secrets.ZIP_NAME }}zip
