name: CI

# 지정한 branch ([main])에서 command(pull)가 수행되면 이 workflow가 동작
on:
  push:
    branches: [main]

  # trigger 없어도 수동 동작
  workflow_dispatch:

env:
  S3_BUCKET_NAME:
  PROJECT_NAME: spring_boot_project
  RESOURCE_PATH: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout release
      uses: action/chectout@v3

    - name: Set up Jdk 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Grant excute permission for gradlew
      run: chmod +x gradlew
      shell: bash

    - name: Build Gradle
      run: ./gradlew build
      shell: bash

    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-key-id: ${{ secrets.SECRET_KEY }}
        aws-region: ${{ secrets.REGION }}
