name: CI

# 지정한 branch ([main])에서 command(pull)가 수행되면 이 workflow가 동작
on:
  push:
    branches: [main]

  # trigger 없어도 수동 동작
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout release
      uses: action/chectout@v3

    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-key-id: ${{ secrets.SECRET_KEY }}
        aws-region: ap-northeast-2
